---
# tasks file for httpd_setup
- name: install HTTPD on remote server
  yum:
    name: "{{ httpd_packages }}"
    state: present
  become: true

- name: place custom HTML file
  copy:
    src: index.html
    dest: /var/www/html/index.html
  become: true

- name: starte the service
  service:
     name: "{{ httpd_packages }}"
     state: started
     enabled: yes
  become: true     
